from typing import Any


BASE_ABILITY_PACK_SOURCE = "mis_base_ability_pack_v1"


def _rule(
    *,
    code: str,
    name: str,
    rule_type: str,
    intent: str,
    priority: int,
    triggers: list[str],
    positive: list[str] | None = None,
    negative: list[str] | None = None,
    targets: list[str] | None = None,
    page_signals: list[str] | None = None,
    success: list[str] | None = None,
    fallback: list[str] | None = None,
    action: dict[str, Any] | None = None,
    risk: str = "low",
    threshold: float = 0.45,
    negative_policy: str = "penalize",
    source: str | None = None,
) -> dict[str, Any]:
    return {
        "rule_code": code,
        "rule_name": name,
        "rule_type": rule_type,
        "intent": intent,
        "status": "active",
        "priority": priority,
        "match_config_json": {
            "trigger_phrases": triggers,
            "positive_actions": positive or [],
            "negative_actions": negative or [],
            "target_keywords": targets or [],
            "page_signals": page_signals or [],
            "negative_policy": negative_policy,
        },
        "action_config_json": action or {"business_target": intent},
        "success_criteria_json": {"criteria": success or []},
        "fallback_strategies_json": {"strategies": fallback or ["request_human_intervention"]},
        "risk_level": risk,
        "confidence_threshold": threshold,
        "source": source or BASE_ABILITY_PACK_SOURCE,
        "production_enabled": True,
    }


BASE_ABILITY_RULES: list[dict[str, Any]] = [
    _rule(
        code="LOGIN-PASSWORD-v1",
        name="账号密码登录",
        rule_type="login",
        intent="完成账号密码登录",
        priority=100,
        triggers=["登录", "账号登录", "密码登录", "进入系统"],
        positive=["登录", "确定", "提交", "进入"],
        targets=["用户名", "密码", "登录按钮"],
        success=["进入首页", "出现工作台", "登录按钮消失"],
        fallback=["check_login_url", "request_human_intervention"],
    ),
    _rule(
        code="LOGIN-SESSION-CHECK-v1",
        name="登录态识别",
        rule_type="login",
        intent="识别当前是否已经登录",
        priority=110,
        triggers=["已登录", "登录态", "会话有效", "无需登录"],
        positive=["检查", "识别", "继续"],
        targets=["首页", "工作台", "用户信息"],
        success=["存在用户菜单", "存在退出登录", "业务菜单可见"],
    ),
    _rule(
        code="GLOBAL-POPUP-CLOSE-v1",
        name="关闭全局非阻塞弹窗",
        rule_type="global_interruption",
        intent="关闭不影响业务的全局提示",
        priority=120,
        triggers=["公告", "通知", "提示", "新手引导"],
        positive=["关闭", "我知道了", "跳过", "稍后"],
        targets=["弹窗", "公告", "遮罩"],
        success=["弹窗消失", "页面主内容可操作"],
    ),
    _rule(
        code="GLOBAL-VERIFY-INTERVENTION-v1",
        name="验证码或二次验证转人工",
        rule_type="global_interruption",
        intent="遇到验证码或二次验证时请求人工介入",
        priority=80,
        triggers=["验证码", "短信验证码", "二次验证", "动态口令"],
        positive=["等待人工输入", "请求人工介入"],
        targets=["验证码", "校验码", "动态口令"],
        success=["人工输入完成", "验证通过"],
        action={"business_target": "人工处理验证", "requires_human": True},
        risk="medium",
    ),
    _rule(
        code="ENTER-TODO-LIST-v1",
        name="进入我的待办",
        rule_type="navigation",
        intent="进入我的待办页面",
        priority=60,
        triggers=["我的待办", "待办事项", "工作台/我的待办", "待处理任务"],
        positive=["进入", "打开", "点击", "查看"],
        targets=["我的待办", "待办事项", "工作台"],
        page_signals=["我的待办", "待办表格", "待办数量"],
        success=["页面出现我的待办", "待办表格可见", "菜单高亮"],
        action={
            "business_target": "进入我的待办业务目标",
            "candidate_paths": ["left_menu", "home_card", "top_navigation", "menu_search", "already_on_page"],
        },
    ),
    _rule(
        code="NAV-MENU-SEARCH-v1",
        name="菜单搜索导航",
        rule_type="navigation",
        intent="通过菜单搜索进入目标功能",
        priority=130,
        triggers=["菜单搜索", "搜索菜单", "找不到菜单", "功能入口"],
        positive=["搜索", "打开", "进入"],
        targets=["菜单", "搜索框", "功能名称"],
        success=["目标菜单高亮", "目标页面标题出现"],
        source="builtin",
    ),
    _rule(
        code="NAV-MENU-PATH-v1",
        name="菜单路径导航",
        rule_type="navigation",
        intent="识别并执行一级、二级、三级菜单路径",
        priority=55,
        triggers=["工作台/我的待办", "系统管理/用户管理", "审批管理/待审批", "菜单路径"],
        positive=["进入", "打开", "导航", "点击"],
        targets=["左侧菜单", "顶部导航", "菜单子项"],
        success=["目标页面标题出现", "目标菜单高亮", "面包屑包含完整路径"],
        action={
            "business_target": "按菜单路径进入目标页面",
            "path_separators": ["/", ">", "-", "→", "\\"],
            "strategies": ["already_on_target_page", "left_menu_path", "top_nav_path", "dashboard_card", "menu_search"],
        },
        source="builtin",
    ),
    _rule(
        code="NAV-ALREADY-ON-TARGET-v1",
        name="已在目标页面判断",
        rule_type="navigation",
        intent="导航前先判断当前页面是否已经达到目标",
        priority=50,
        triggers=["已在目标页", "当前页面", "页面标题", "面包屑", "菜单高亮"],
        positive=["跳过点击", "直接验证"],
        targets=["页面标题", "主内容", "面包屑", "高亮菜单"],
        success=["检测到目标页面强证据"],
        source="builtin",
    ),
    _rule(
        code="NAV-EXPAND-PARENT-v1",
        name="展开父级菜单",
        rule_type="navigation",
        intent="找到父级菜单后展开并查找子菜单",
        priority=58,
        triggers=["折叠菜单", "父级菜单", "子菜单不可见"],
        positive=["展开", "点击父菜单", "查找子菜单"],
        targets=["一级菜单", "二级菜单", "树形菜单"],
        success=["子菜单可见", "父菜单展开"],
        source="builtin",
    ),
    _rule(
        code="NAV-DASHBOARD-CARD-v1",
        name="首页卡片入口导航",
        rule_type="navigation",
        intent="通过工作台卡片或快捷入口进入目标页面",
        priority=95,
        triggers=["首页卡片", "快捷入口", "工作台卡片", "我的待办卡片"],
        positive=["点击卡片", "打开快捷入口"],
        targets=["卡片", "快捷入口", "待办事项"],
        success=["目标页面标题出现", "目标列表可见"],
        source="builtin",
    ),
    _rule(
        code="QUERY-FILTER-SUBMIT-v1",
        name="条件查询",
        rule_type="query",
        intent="填写查询条件并执行查询",
        priority=100,
        triggers=["查询", "筛选", "检索", "搜索数据"],
        positive=["查询", "搜索", "筛选"],
        targets=["查询条件", "筛选条件", "查询按钮"],
        success=["表格刷新", "结果区域可见", "查询完成"],
    ),
    _rule(
        code="QUERY-FILTER-RESET-v1",
        name="重置查询条件",
        rule_type="query",
        intent="清空查询条件并恢复默认结果",
        priority=120,
        triggers=["重置", "清空条件", "恢复默认", "重新查询"],
        positive=["重置", "清空", "恢复"],
        targets=["重置按钮", "查询条件"],
        success=["条件清空", "默认结果可见"],
    ),
    _rule(
        code="CREATE-OPEN-FORM-v1",
        name="打开新增表单",
        rule_type="create",
        intent="打开新增业务数据表单",
        priority=100,
        triggers=["新增", "新建", "创建", "添加"],
        positive=["新增", "新建", "创建", "添加"],
        targets=["新增按钮", "创建按钮", "表单"],
        success=["新增表单可见", "保存按钮可见"],
        risk="medium",
    ),
    _rule(
        code="CREATE-SUBMIT-FORM-v1",
        name="提交新增表单",
        rule_type="create",
        intent="提交新增业务数据",
        priority=110,
        triggers=["保存新增", "提交新增", "创建记录", "新增保存"],
        positive=["保存", "提交", "确定"],
        targets=["保存按钮", "提交按钮", "新增表单"],
        success=["保存成功", "新增成功", "列表出现新记录"],
        risk="medium",
    ),
    _rule(
        code="UPDATE-OPEN-FORM-v1",
        name="打开编辑表单",
        rule_type="update",
        intent="打开已有业务数据编辑表单",
        priority=100,
        triggers=["编辑", "修改", "更新", "调整"],
        positive=["编辑", "修改", "更新"],
        targets=["编辑按钮", "修改按钮", "表格行"],
        success=["编辑表单可见", "保存按钮可见"],
        risk="medium",
    ),
    _rule(
        code="UPDATE-SUBMIT-FORM-v1",
        name="提交编辑表单",
        rule_type="update",
        intent="保存已有业务数据修改",
        priority=110,
        triggers=["保存修改", "提交修改", "更新记录", "编辑保存"],
        positive=["保存", "提交", "确定"],
        targets=["保存按钮", "提交按钮", "编辑表单"],
        success=["保存成功", "更新成功", "列表显示新值"],
        risk="medium",
    ),
    _rule(
        code="DELETE-SOFT-v1",
        name="删除单条记录",
        rule_type="delete",
        intent="删除指定业务记录",
        priority=100,
        triggers=["删除", "移除", "作废"],
        positive=["删除", "移除", "作废", "确定"],
        targets=["删除按钮", "表格行", "确认弹窗"],
        success=["删除成功", "记录消失", "状态变为已作废"],
        risk="high",
    ),
    _rule(
        code="DELETE-BATCH-CONFIRM-v1",
        name="批量删除确认",
        rule_type="delete",
        intent="批量删除选中业务记录",
        priority=110,
        triggers=["批量删除", "批量移除", "批量作废"],
        positive=["全选", "勾选", "批量删除", "确定"],
        targets=["复选框", "批量删除按钮", "确认弹窗"],
        success=["批量删除成功", "选中记录消失"],
        risk="high",
    ),
    _rule(
        code="TABLE-SELECT-ROW-v1",
        name="选择表格行",
        rule_type="table_operation",
        intent="在表格中选择目标行",
        priority=100,
        triggers=["选择行", "勾选记录", "选中数据", "定位记录"],
        positive=["选择", "勾选", "点击行"],
        targets=["表格", "复选框", "目标行"],
        success=["目标行被选中", "行高亮", "操作按钮可用"],
    ),
    _rule(
        code="TABLE-PAGINATION-v1",
        name="表格翻页查找",
        rule_type="table_operation",
        intent="通过翻页定位表格数据",
        priority=120,
        triggers=["下一页", "翻页", "分页", "找记录"],
        positive=["下一页", "上一页", "跳页", "刷新"],
        targets=["分页器", "表格"],
        success=["目标记录出现", "页码变化"],
    ),
    _rule(
        code="DETAIL-OPEN-v1",
        name="打开详情页",
        rule_type="detail_navigation",
        intent="打开业务记录详情",
        priority=100,
        triggers=["详情", "查看详情", "明细", "打开记录"],
        positive=["详情", "查看", "打开"],
        targets=["详情按钮", "表格行", "记录标题"],
        success=["详情页标题可见", "详情字段可见"],
    ),
    _rule(
        code="DETAIL-BACK-v1",
        name="从详情返回列表",
        rule_type="detail_navigation",
        intent="从详情页返回业务列表",
        priority=120,
        triggers=["返回列表", "回到列表", "返回上一页", "关闭详情"],
        positive=["返回", "关闭", "取消"],
        targets=["返回按钮", "关闭按钮", "面包屑"],
        success=["列表页可见", "查询条件保留"],
    ),
    _rule(
        code="APPROVAL-PASS-v1",
        name="审批通过",
        rule_type="approval_workflow",
        intent="审批通过业务目标",
        priority=50,
        triggers=["审批通过", "审核通过", "同意申请", "批准"],
        positive=["审批", "审核", "办理", "处理", "通过", "同意", "批准"],
        negative=["查看审批流程", "审批记录", "流程图", "历史", "详情"],
        targets=["审批按钮", "审核按钮", "同意按钮", "通过按钮"],
        success=["审批成功", "审核成功", "状态变为已通过", "待办消失"],
        action={
            "business_target": "审批通过业务目标",
            "runtime_message": "命中规则 APPROVAL-PASS-v1：将按审批通过业务目标执行。",
        },
        risk="high",
        negative_policy="exclude",
    ),
    _rule(
        code="APPROVAL-FLOW-VIEW-v1",
        name="查看审批流程",
        rule_type="approval_workflow",
        intent="查看审批流程业务目标",
        priority=55,
        triggers=["查看审批流程", "审批流程", "流程图"],
        positive=["查看审批流程", "流程图", "审批记录"],
        negative=["审批通过", "审核通过", "同意申请", "批准"],
        targets=["流程图", "审批记录", "流程节点"],
        success=["流程图可见", "审批记录可见", "节点信息可见"],
        action={
            "business_target": "查看审批流程业务目标",
            "must_not_select": ["APPROVAL-PASS-v1"],
        },
        negative_policy="penalize",
    ),
    _rule(
        code="FORM-SELECT-DROPDOWN-v1",
        name="下拉控件选择",
        rule_type="form_control",
        intent="在下拉控件中选择目标值",
        priority=100,
        triggers=["下拉选择", "选择选项", "选择类型", "选择状态"],
        positive=["选择", "展开", "点击选项"],
        targets=["下拉框", "选择器", "选项"],
        success=["目标选项被选中", "控件显示目标值"],
    ),
    _rule(
        code="FORM-DATE-RANGE-v1",
        name="日期范围输入",
        rule_type="form_control",
        intent="填写日期或日期范围",
        priority=110,
        triggers=["日期", "时间范围", "开始日期", "结束日期"],
        positive=["选择日期", "输入日期", "确认日期"],
        targets=["日期控件", "开始日期", "结束日期"],
        success=["日期值显示正确", "查询条件包含日期"],
    ),
    _rule(
        code="ASSERT-SUCCESS-MESSAGE-v1",
        name="成功提示断言",
        rule_type="assertion",
        intent="断言页面出现成功提示",
        priority=100,
        triggers=["断言成功", "检查成功提示", "验证保存成功", "验证提交成功"],
        positive=["检查", "断言", "验证"],
        targets=["成功提示", "消息条", "Toast"],
        success=["出现成功提示", "提示文本匹配"],
    ),
    _rule(
        code="ASSERT-STATUS-CHANGED-v1",
        name="状态变化断言",
        rule_type="assertion",
        intent="断言业务状态发生预期变化",
        priority=110,
        triggers=["状态变为", "检查状态", "验证状态", "状态更新"],
        positive=["检查", "断言", "验证"],
        targets=["状态字段", "表格状态", "详情状态"],
        success=["状态文本匹配", "状态标签可见"],
    ),
    _rule(
        code="DIALOG-CONFIRM-ACCEPT-v1",
        name="确认弹窗同意",
        rule_type="dialog_handler",
        intent="处理确认类弹窗",
        priority=100,
        triggers=["确认弹窗", "是否确认", "请确认", "二次确认"],
        positive=["确定", "确认", "同意", "继续"],
        targets=["确认按钮", "确定按钮", "弹窗"],
        success=["弹窗关闭", "操作继续"],
        risk="medium",
    ),
    _rule(
        code="DIALOG-CLOSE-NONBLOCKING-v1",
        name="关闭非阻塞弹窗",
        rule_type="dialog_handler",
        intent="关闭不影响当前目标的弹窗",
        priority=120,
        triggers=["关闭弹窗", "提示弹窗", "公告弹窗", "遮挡"],
        positive=["关闭", "取消", "我知道了"],
        targets=["关闭按钮", "弹窗", "遮罩"],
        success=["弹窗消失", "目标元素可见"],
    ),
    _rule(
        code="RISK-BLOCK-DESTRUCTIVE-v1",
        name="阻止未授权高风险操作",
        rule_type="risk_policy",
        intent="阻止未授权删除或作废操作",
        priority=40,
        triggers=["删除", "作废", "批量删除", "不可恢复"],
        positive=["阻止", "请求确认", "人工介入"],
        targets=["删除按钮", "作废按钮"],
        success=["操作暂停", "产生人工介入请求"],
        action={"business_target": "高风险操作拦截", "requires_human": True},
        risk="high",
    ),
    _rule(
        code="RISK-APPROVAL-AND-FINANCE-v1",
        name="审批和金额变更需确认",
        rule_type="risk_policy",
        intent="审批或金额变更前执行风险确认",
        priority=45,
        triggers=["审批", "付款", "金额", "退款", "结算"],
        positive=["请求确认", "暂停", "人工介入"],
        targets=["金额字段", "审批按钮", "付款按钮"],
        success=["确认记录已生成", "操作等待人工确认"],
        action={"business_target": "敏感业务确认", "requires_human": True},
        risk="high",
    ),
    _rule(
        code="VISION-LOCATOR-FALLBACK-v1",
        name="视觉定位兜底",
        rule_type="vision_fallback",
        intent="元素定位失败后使用视觉兜底",
        priority=150,
        triggers=["找不到元素", "定位失败", "元素变化", "按钮不可见"],
        positive=["视觉识别", "截图识别", "兜底定位"],
        targets=["按钮", "输入框", "菜单"],
        success=["视觉识别到候选元素", "候选元素置信度达标"],
        action={"business_target": "视觉定位兜底", "uses_vision": True},
        risk="medium",
    ),
    _rule(
        code="VISION-ASSERTION-FALLBACK-v1",
        name="视觉断言兜底",
        rule_type="vision_fallback",
        intent="文本或结构断言失败后使用视觉确认",
        priority=160,
        triggers=["断言失败", "文本未找到", "页面变化", "截图确认"],
        positive=["视觉确认", "截图比对", "兜底断言"],
        targets=["页面区域", "状态标签", "提示信息"],
        success=["视觉判断通过", "人工可复核截图"],
        action={"business_target": "视觉断言兜底", "uses_vision": True},
        risk="medium",
    ),
    _rule(
        code="RECOVERY-RETRY-LOADING-v1",
        name="加载延迟后重试",
        rule_type="recovery_policy",
        intent="页面加载慢时等待并重试当前动作",
        priority=130,
        triggers=["加载中", "超时", "网络慢", "按钮暂不可用"],
        positive=["等待", "重试", "刷新状态"],
        targets=["加载遮罩", "按钮", "表格"],
        success=["加载结束", "动作重试成功"],
        action={"business_target": "等待重试恢复", "max_retry": 2},
    ),
    _rule(
        code="RECOVERY-REFRESH-STALE-v1",
        name="页面失效刷新恢复",
        rule_type="recovery_policy",
        intent="页面状态失效时刷新后恢复执行",
        priority=140,
        triggers=["页面失效", "会话过期", "空白页", "数据未刷新"],
        positive=["刷新", "重新进入", "恢复"],
        targets=["页面", "表格", "会话"],
        success=["页面恢复", "目标元素重新出现"],
        action={"business_target": "刷新恢复", "max_retry": 1},
        risk="medium",
    ),
]


def _structured_rule(
    *,
    code: str,
    name: str,
    rule_type: str,
    intent: str,
    priority: int,
    match: dict[str, Any],
    action: dict[str, Any],
    success: list[str],
    fallback: list[str] | None = None,
    risk: str = "low",
    threshold: float = 0.65,
) -> dict[str, Any]:
    return {
        "rule_code": code,
        "rule_name": name,
        "rule_type": rule_type,
        "intent": intent,
        "status": "active",
        "priority": priority,
        "match_config_json": match,
        "action_config_json": action,
        "success_criteria_json": {"criteria": success},
        "fallback_strategies_json": {"strategies": fallback or ["request_human_intervention"]},
        "risk_level": risk,
        "confidence_threshold": threshold,
        "source": BASE_ABILITY_PACK_SOURCE,
        "production_enabled": True,
    }


COMMON_FIELD_DEFAULTS = {
    "用户名": "test_ai_${timestamp}",
    "姓名": "测试用户${timestamp}",
    "手机号": "13800000000",
    "邮箱": "test_${timestamp}@example.com",
    "备注": "自动化测试",
    "审批意见": "自动化测试审批通过",
    "标题": "自动化测试标题${timestamp}",
    "编号": "AUTO_${timestamp}",
}


BASE_ABILITY_RULES.extend(
    [
        _structured_rule(
            code="FORM-FILL-TEXT-v1",
            name="通用文本字段填写",
            rule_type="form_fill",
            intent="fill_text_field",
            priority=70,
            match={
                "fieldTypes": ["input", "textarea"],
                "matchBy": ["label", "placeholder", "aria-label", "nearbyText", "formItemLabel"],
                "ignoreHidden": True,
                "ignoreReadonly": True,
            },
            action={
                "clearBeforeInput": True,
                "inputMethod": "fill",
                "verifyValue": True,
                "defaultValues": COMMON_FIELD_DEFAULTS,
                "unknownRequiredField": "needs_clarification",
            },
            success=["field_value_equals", "no_validation_error"],
            fallback=["retry_by_nearby_label", "request_test_data", "human_intervention"],
        ),
        _structured_rule(
            code="FORM-FILL-CONTAINER-v1",
            name="分组和弹层表单填写",
            rule_type="form_fill",
            intent="fill_grouped_or_overlay_form",
            priority=75,
            match={
                "containers": ["form", "dialog", "drawer", "tab_panel", "form_item"],
                "matchBy": ["groupTitle", "tabTitle", "fieldLabel", "nearbyText"],
                "skip": ["hidden", "readonly", "disabled"],
            },
            action={
                "switchTabsIfNeeded": True,
                "fillVisibleRequiredFirst": True,
                "retryAfterValidationError": True,
                "defaultValues": COMMON_FIELD_DEFAULTS,
            },
            success=["required_fields_filled", "no_validation_error"],
            fallback=["open_next_tab", "request_missing_required_fields", "human_intervention"],
        ),
        _structured_rule(
            code="DROPDOWN-SELECT-OPTION-v1",
            name="下拉框选择选项",
            rule_type="dropdown",
            intent="select_dropdown_option",
            priority=70,
            match={
                "controlTypes": ["select", "combobox", "custom_select"],
                "triggerBy": ["label", "placeholder", "nearbyText"],
                "optionMatch": ["exact", "contains", "semantic"],
                "allowSearch": True,
                "allowKeyboard": True,
            },
            action={
                "openDropdown": ["click_control", "keyboard_arrow_down"],
                "searchIfNeeded": True,
                "selectOption": ["click_option", "keyboard_enter"],
                "verifySelected": True,
                "commonDefaults": {"状态": ["启用", "有效", "正常"], "是否": "是", "审批结果": "通过", "性别": "男"},
            },
            success=["selected_value_visible", "form_value_updated"],
            fallback=["retry_open_dropdown", "scroll_options", "search_option_text", "llm_choose_option", "vision_fallback"],
        ),
        _structured_rule(
            code="DROPDOWN-KEY-FIELD-v1",
            name="关键下拉字段追问",
            rule_type="dropdown",
            intent="ask_before_selecting_key_dropdown",
            priority=60,
            match={
                "criticalLabels": ["组织机构", "角色", "数据权限", "所属单位", "审批角色"],
                "noUserValuePolicy": "needs_clarification",
                "defaultFirstOptionAllowedOnlyWhenConfigured": True,
            },
            action={"askForValue": True, "doNotPickRandomOption": True},
            success=["clarification_requested"],
            risk="medium",
        ),
        _structured_rule(
            code="DATE-PICKER-v1",
            name="日期选择器填写",
            rule_type="date_picker",
            intent="select_date",
            priority=70,
            match={
                "controlTypes": ["date_input", "date_picker", "datetime_picker", "date_range"],
                "matchBy": ["label", "placeholder", "nearbyText"],
                "dateFormats": ["YYYY-MM-DD", "YYYY/MM/DD", "YYYY-MM-DD HH:mm:ss"],
            },
            action={
                "preferDirectInput": True,
                "openPickerIfDirectInputFails": True,
                "defaultDate": "today",
                "verifyValue": True,
                "fieldDefaults": {
                    "申请日期": "today",
                    "开始日期": "today",
                    "结束日期": "today+7d",
                    "有效期开始": "today",
                    "有效期结束": "today+30d",
                    "计划完成时间": "today+7d",
                },
            },
            success=["date_value_visible", "date_is_allowed"],
            fallback=["open_picker", "choose_next_enabled_date", "request_clarification"],
        ),
        _structured_rule(
            code="DATE-RANGE-PICKER-v1",
            name="日期范围填写",
            rule_type="date_picker",
            intent="select_date_range",
            priority=75,
            match={"controlTypes": ["date_range", "start_end_inputs"], "labels": ["开始日期", "结束日期", "起止时间"]},
            action={"defaultStart": "today", "defaultEnd": "today+7d", "verifyRange": True},
            success=["start_and_end_values_visible", "range_order_valid"],
            fallback=["direct_input_range", "picker_select_range", "request_clarification"],
        ),
        _structured_rule(
            code="ORG-SELECTOR-v1",
            name="组织机构选择",
            rule_type="org_selector",
            intent="select_organization",
            priority=60,
            match={
                "fieldLabels": ["组织机构", "所属机构", "部门", "所属部门", "单位", "所属单位"],
                "controlTypes": ["tree_select", "modal_tree", "dropdown_tree"],
                "allowDefault": False,
            },
            action={"openSelector": True, "searchIfValueProvided": True, "expandTree": True, "selectNode": True, "confirmIfNeeded": True},
            success=["organization_value_backfilled"],
            fallback=["needs_clarification", "human_intervention"],
            risk="medium",
        ),
        _structured_rule(
            code="ORG-SELECTOR-DEFAULT-v1",
            name="允许默认机构选择",
            rule_type="org_selector",
            intent="select_default_organization_when_allowed",
            priority=90,
            match={"fieldLabels": ["当前机构", "本部门"], "allowDefault": True, "defaultSources": ["current_user_org", "first_available_org"]},
            action={"selectCurrentUserOrgFirst": True, "confirmIfNeeded": True},
            success=["organization_value_backfilled"],
            fallback=["request_clarification"],
        ),
        _structured_rule(
            code="PERSON-SELECTOR-v1",
            name="人员选择",
            rule_type="person_selector",
            intent="select_person",
            priority=60,
            match={
                "fieldLabels": ["人员", "负责人", "经办人", "申请人", "审批人", "处理人"],
                "controlTypes": ["person_selector", "modal_selector", "tree_person_selector"],
                "allowCurrentUserDefault": True,
            },
            action={"openSelector": True, "searchIfValueProvided": True, "selectPerson": True, "confirmIfNeeded": True, "verifySelected": True},
            success=["person_value_backfilled"],
            fallback=["request_person_value", "human_intervention"],
            risk="medium",
        ),
        _structured_rule(
            code="PERSON-APPROVER-ASK-v1",
            name="审批人字段追问",
            rule_type="person_selector",
            intent="ask_before_selecting_approver",
            priority=55,
            match={"fieldLabels": ["审批人", "审核人", "批准人"], "noUserValuePolicy": "needs_clarification"},
            action={"askForPerson": True, "doNotUseRandomPerson": True},
            success=["clarification_requested"],
            risk="high",
        ),
        _structured_rule(
            code="TREE-SELECTOR-v1",
            name="树节点选择",
            rule_type="tree_selector",
            intent="select_tree_node",
            priority=80,
            match={"treeTypes": ["category", "area", "device", "dictionary", "organization"], "supportsSearch": True, "lazyLoad": True},
            action={"openTree": True, "searchNode": True, "expandParents": True, "selectNode": True},
            success=["tree_node_selected"],
            fallback=["expand_more_nodes", "search_node_text", "request_clarification"],
        ),
        _structured_rule(
            code="TREE-LAZY-LOAD-v1",
            name="懒加载树展开",
            rule_type="tree_selector",
            intent="expand_lazy_tree",
            priority=90,
            match={"signals": ["展开", "加载更多", "子节点"], "lazyLoad": True},
            action={"expandTree": True, "waitForChildren": True, "retrySearch": True},
            success=["children_loaded"],
            fallback=["retry_expand", "human_intervention"],
        ),
        _structured_rule(
            code="DIALOG-SELECTOR-v1",
            name="弹窗列表选择",
            rule_type="dialog_selector",
            intent="select_from_dialog",
            priority=80,
            match={"triggerLabels": ["选择", "请选择", "选择人员", "选择设备"], "dialogContains": ["查询", "确定"]},
            action={"openDialog": True, "queryTarget": True, "selectTableRow": True, "confirm": True, "verifyBackfill": True},
            success=["dialog_closed", "field_backfilled"],
            fallback=["retry_query", "select_first_matching_row", "request_clarification"],
        ),
        _structured_rule(
            code="DIALOG-MULTI-SELECT-v1",
            name="弹窗多选回填",
            rule_type="dialog_selector",
            intent="select_multiple_from_dialog",
            priority=90,
            match={"dialogContains": ["全选", "勾选", "确定"], "multiSelect": True},
            action={"openDialog": True, "selectRows": True, "confirm": True, "verifyBackfill": True},
            success=["selected_values_backfilled"],
            fallback=["request_target_values", "human_intervention"],
        ),
        _structured_rule(
            code="FILE-UPLOAD-INPUT-v1",
            name="原生文件上传",
            rule_type="file_upload",
            intent="upload_file_input",
            priority=80,
            match={"controlTypes": ["input[type=file]"], "matchBy": ["label", "nearbyText"], "requiresUserFile": True},
            action={"setInputFiles": True, "verifyAttachmentList": True},
            success=["file_name_visible", "upload_success_message"],
            fallback=["request_file_path"],
            risk="medium",
        ),
        _structured_rule(
            code="FILE-UPLOAD-CUSTOM-v1",
            name="自定义上传控件",
            rule_type="file_upload",
            intent="upload_file_custom_control",
            priority=90,
            match={"controlTypes": ["upload_button", "dropzone"], "signals": ["上传", "附件", "拖拽"], "requiresUserFile": True},
            action={"clickUploadButton": True, "setInputFilesWhenInputAppears": True, "verifyUploadResult": True},
            success=["attachment_list_updated"],
            fallback=["request_file_path", "human_intervention"],
            risk="medium",
        ),
    ]
)
