from typing import Any


COMMON_OPERATION_PACK_VERSION = "1.0.0"
COMMON_OPERATION_PACK_SOURCE = "builtin"


def _rule(
    *,
    code: str,
    name: str,
    rule_type: str,
    intent: str,
    priority: int,
    match: dict[str, Any],
    action: dict[str, Any],
    success: list[str],
    fallback: list[str] | None = None,
    failure: list[str] | None = None,
    recovery: list[str] | None = None,
    risk: str = "low",
    threshold: float = 0.55,
) -> dict[str, Any]:
    resolved_fallback = fallback or ["request_human_intervention"]
    return {
        "rule_code": code,
        "rule_name": name,
        "rule_type": rule_type,
        "intent": intent,
        "status": "active",
        "priority": priority,
        "match_config_json": match,
        "action_config_json": {
            **action,
            "runtime_message_template": f"命中规则 {code}：将按{name}执行。",
        },
        "success_criteria_json": {"criteria": success},
        "fallback_strategies_json": {"strategies": resolved_fallback},
        "failure_patterns_json": {"patterns": failure or []},
        "recovery_strategies_json": {"strategies": recovery or resolved_fallback},
        "risk_level": risk,
        "confidence_threshold": threshold,
        "auto_handle": risk == "low",
        "requires_human_confirmation": risk == "high" or bool(action.get("requires_human")),
        "production_enabled": True,
        "source": COMMON_OPERATION_PACK_SOURCE,
        "version": COMMON_OPERATION_PACK_VERSION,
    }


COMMON_FIELD_DEFAULTS = {
    "用户名": "test_ai_${timestamp}",
    "姓名": "测试用户${timestamp}",
    "手机号": "13800000000",
    "邮箱": "test_${timestamp}@example.com",
    "备注": "自动化测试",
    "审批意见": "自动化测试审批通过",
    "标题": "自动化测试标题${timestamp}",
    "编号": "AUTO_${timestamp}",
}


DATE_DEFAULTS = {
    "开始日期": "today",
    "结束日期": "today+7d",
    "有效期开始": "today",
    "有效期结束": "today+30d",
    "出差开始": "today",
    "出差结束": "today+1d",
}


COMMON_OPERATION_RULES: list[dict[str, Any]] = [
    _rule(
        code="LOGIN-USERNAME-PASSWORD-v1",
        name="用户名密码登录",
        rule_type="login",
        intent="username_password_login",
        priority=40,
        match={
            "fields": ["username", "password"],
            "usernameSignals": ["用户名", "账号", "用户", "loginName", "userid", "userName"],
            "passwordSignals": ["密码", "口令", "password", "pwd"],
            "submitSignals": ["登录", "Login", "进入系统", "提交"],
        },
        action={"fillUsername": True, "fillPassword": True, "clickSubmit": True, "redactPassword": True},
        success=["login_button_disappears", "home_or_menu_visible", "business_url_reached"],
        failure=["login_failed", "blocking_dialog_detected"],
        recovery=["handle_global_interruption", "retry_submit_once", "request_human_intervention"],
    ),
    _rule(
        code="LOGIN-SUCCESS-DETECT-v1",
        name="登录成功判断",
        rule_type="login",
        intent="login_success_detect",
        priority=45,
        match={
            "successSignals": ["主菜单", "首页", "工作台", "用户信息", "退出", "个人中心"],
            "urlSignals": ["/home", "/dashboard", "/workbench", "/index", "/portal"],
        },
        action={"detectMainMenu": True, "detectHomePage": True, "detectUserArea": True},
        success=["main_menu_visible", "home_page_visible", "user_info_visible"],
        failure=["login_failed"],
        recovery=["wait_for_page_ready", "handle_login_interruption"],
    ),
    _rule(
        code="LOGIN-ACCOUNT-EXPIRY-v1",
        name="账号到期提醒处理",
        rule_type="login",
        intent="handle_account_expiry_notice",
        priority=50,
        match={
            "noticeTexts": ["用户账号将于", "账号即将到期", "到期之后系统将禁用", "联系管理员"],
            "continueButtons": ["继续访问", "继续", "进入系统", "我知道了", "确定"],
        },
        action={"clickLowRiskContinue": True, "continueButtons": ["继续访问", "继续", "进入系统", "我知道了", "确定"]},
        success=["notice_closed", "login_or_home_continues"],
        failure=["account_expired"],
        recovery=["request_human_intervention"],
    ),
    _rule(
        code="LOGIN-PASSWORD-EXPIRY-v1",
        name="密码到期提醒处理",
        rule_type="login",
        intent="handle_password_expiry_notice",
        priority=55,
        match={
            "noticeTexts": ["密码即将过期", "密码将于", "请修改密码"],
            "safeContinueButtons": ["稍后修改", "继续访问", "暂不修改", "我知道了"],
            "forceSignals": ["必须修改", "强制修改", "无法继续"],
        },
        action={"autoContinueWhenSafeButtonExists": True, "forceChangePolicy": "needs_human"},
        success=["safe_notice_closed_or_human_requested"],
        failure=["forced_password_change"],
        recovery=["request_human_intervention"],
        risk="medium",
    ),
    _rule(
        code="LOGIN-FORCE-CHANGE-PASSWORD-v1",
        name="强制修改密码转人工",
        rule_type="login",
        intent="force_change_password",
        priority=35,
        match={"forceSignals": ["首次登录", "强制修改密码", "必须修改初始密码", "修改初始密码"]},
        action={"requires_human": True, "policy": "needs_human"},
        success=["human_intervention_created"],
        fallback=["request_human_intervention"],
        failure=["forced_password_change"],
        recovery=["request_human_intervention"],
        risk="high",
    ),
    _rule(
        code="INTERRUPT-LOW-RISK-CONTINUE-v1",
        name="低风险中断继续",
        rule_type="global_interruption",
        intent="handle_low_risk_continue",
        priority=50,
        match={"buttonTexts": ["继续访问", "我知道了", "确定", "关闭", "继续"], "risk": "low"},
        action={"clickAllowedButtons": ["继续访问", "我知道了", "确定", "关闭", "继续"], "verifyMainPageOperable": True},
        success=["interruption_closed", "main_page_operable"],
        failure=["blocking_dialog_detected"],
        recovery=["request_human_intervention"],
    ),
    _rule(
        code="INTERRUPT-BLOCKING-MODAL-v1",
        name="阻塞弹窗识别",
        rule_type="global_interruption",
        intent="detect_blocking_modal",
        priority=55,
        match={"signals": ["modal", "dialog", "overlay", "mask", "居中弹窗", "主界面不可操作"]},
        action={"detectOverlay": True, "detectMainPageBlocked": True, "captureEvidence": True},
        success=["blocking_modal_classified"],
        failure=["blocking_dialog_detected"],
        recovery=["close_when_low_risk", "request_human_intervention"],
        risk="medium",
    ),
    _rule(
        code="INTERRUPT-NON-BLOCKING-NOTICE-v1",
        name="非阻塞提示忽略",
        rule_type="global_interruption",
        intent="ignore_non_blocking_notice",
        priority=60,
        match={"mainPageSignals": ["主菜单可见", "页面可操作"], "noticeSignals": ["公告", "提示", "通知"]},
        action={"doNotBlockFlowWhenMainPageOperable": True, "recordNoticeOnly": True},
        success=["main_page_operable"],
        failure=["non_blocking_notice_detected"],
        recovery=["continue_current_step"],
    ),
    _rule(
        code="INTERRUPT-SESSION-TIMEOUT-v1",
        name="会话超时处理",
        rule_type="global_interruption",
        intent="handle_session_timeout",
        priority=45,
        match={"texts": ["请重新登录", "登录超时", "会话过期", "session timeout", "重新登录"]},
        action={"tryReloginWhenCredentialsAvailable": True, "recordFailureWhenUnavailable": True},
        success=["relogin_succeeded_or_failure_recorded"],
        failure=["login_failed"],
        recovery=["relogin", "request_human_intervention"],
        risk="medium",
    ),
    _rule(
        code="NAV-IFRAME-MENU-v1",
        name="iframe 内菜单导航",
        rule_type="navigation",
        intent="navigate_iframe_menu",
        priority=75,
        match={"containers": ["iframe", "frame"], "menuSignals": ["menu", "nav", "sidebar", "ant-menu", "el-menu"]},
        action={"scanFrames": True, "repeatMenuPathStrategiesInFrame": True},
        success=["target_menu_clicked_in_frame", "target_page_evidence_detected"],
        failure=["menu_parent_not_found", "menu_child_not_found", "navigation_goal_not_reached"],
        recovery=["try_parent_page_menu", "try_menu_search", "request_human_intervention"],
    ),
    _rule(
        code="QUERY-KEYWORD-v1",
        name="关键字查询",
        rule_type="query",
        intent="query_list",
        priority=70,
        match={"fieldLabels": ["关键字", "关键词", "名称", "编号", "申请人"], "buttonTexts": ["查询", "搜索", "检索"]},
        action={"fillKeyword": True, "clickQuery": True, "waitForRefresh": True},
        success=["table_refreshed", "loading_disappeared"],
        failure=["table_not_found"],
        recovery=["expand_advanced_query", "reobserve_page"],
    ),
    _rule(
        code="QUERY-ADVANCED-EXPAND-v1",
        name="高级查询展开",
        rule_type="query",
        intent="expand_advanced_query",
        priority=90,
        match={"triggerTexts": ["高级查询", "更多条件", "展开", "筛选"], "collapsedSignals": ["收起", "更多"]},
        action={"expandPanel": True, "fillVisibleConditions": True},
        success=["advanced_fields_visible"],
        failure=["click_no_effect"],
        recovery=["try_nearby_filter_panel", "request_human_intervention"],
    ),
    _rule(
        code="QUERY-DATE-RANGE-v1",
        name="日期范围查询",
        rule_type="query",
        intent="query_list",
        priority=80,
        match={"fieldLabels": ["开始日期", "结束日期", "起止时间", "申请日期", "创建时间"], "usesRuleType": "date_picker"},
        action={"useDatePickerRules": True, "defaultDates": DATE_DEFAULTS, "clickQueryAfterFill": True},
        success=["date_conditions_applied", "table_refreshed"],
        failure=["date_not_selectable"],
        recovery=["choose_next_enabled_date", "request_clarification"],
    ),
    _rule(
        code="QUERY-DROPDOWN-v1",
        name="下拉条件查询",
        rule_type="query",
        intent="query_list",
        priority=85,
        match={"fieldLabels": ["状态", "类型", "分类", "是否"], "usesRuleType": "dropdown"},
        action={"useDropdownRules": True, "clickQueryAfterFill": True},
        success=["dropdown_condition_applied", "table_refreshed"],
        failure=["dropdown_option_not_found"],
        recovery=["request_clarification", "clear_optional_condition"],
    ),
    _rule(
        code="QUERY-RESULT-REFRESH-v1",
        name="查询结果刷新验证",
        rule_type="query",
        intent="query_result_refresh",
        priority=65,
        match={"signals": ["loading", "spin", "查询中", "加载中", "表格刷新"]},
        action={"waitLoadingGone": True, "compareTableBeforeAfter": True, "captureResultEvidence": True},
        success=["loading_disappeared", "table_visible"],
        failure=["table_not_found"],
        recovery=["wait_and_retry", "reobserve_page"],
    ),
    _rule(
        code="QUERY-NO-DATA-v1",
        name="无数据结果识别",
        rule_type="query",
        intent="query_no_data",
        priority=95,
        match={"emptySignals": ["暂无数据", "无数据", "没有数据", "未查询到", "No Data"]},
        action={"treatEmptyResultAsValidWhenAllowed": True, "recordRowCountZero": True},
        success=["empty_state_detected"],
        failure=["table_no_data_rows"],
        recovery=["continue_when_empty_allowed", "request_clarification"],
    ),
    _rule(
        code="TABLE-DETECT-BASIC-v1",
        name="基础表格识别",
        rule_type="table_detection",
        intent="detect_table",
        priority=50,
        match={"selectors": ["table", "[role=grid]", ".ant-table", ".el-table", ".vxe-table"], "visibleOnly": True},
        action={"detectContainer": True, "detectHeaders": True, "detectRows": True},
        success=["table_container_visible"],
        failure=["table_not_found"],
        recovery=["wait_for_page_ready", "try_grid_role"],
    ),
    _rule(
        code="TABLE-HEADER-MAP-v1",
        name="表头列名映射",
        rule_type="table_detection",
        intent="map_table_headers",
        priority=60,
        match={"headerSelectors": ["th", ".ant-table-thead", ".el-table__header", "[role=columnheader]"]},
        action={"extractHeaders": True, "normalizeColumnNames": True, "mapColumnIndexes": True},
        success=["header_map_created"],
        failure=["table_not_found"],
        recovery=["try_accessibility_grid", "try_visible_text_headers"],
    ),
    _rule(
        code="TABLE-DATA-ROW-v1",
        name="真实数据行识别",
        rule_type="table_detection",
        intent="detect_data_rows",
        priority=65,
        match={"rowSelectors": ["tbody tr", ".ant-table-row", ".el-table__row", "[role=row]"], "mustContainCell": True},
        action={"extractDataRows": True, "ignoreHiddenRows": True, "assignRowRefs": True},
        success=["data_rows_detected_or_empty_state_detected"],
        failure=["table_no_data_rows"],
        recovery=["wait_for_rows", "detect_empty_state"],
    ),
    _rule(
        code="TABLE-NON-DATA-ROW-v1",
        name="非数据行过滤",
        rule_type="table_detection",
        intent="filter_non_data_rows",
        priority=66,
        match={"nonDataSignals": ["分页", "合计", "总计", "展开详情", "skeleton", "loading", "placeholder"]},
        action={"filterPaginationRows": True, "filterSummaryRows": True, "filterSkeletonRows": True},
        success=["non_data_rows_filtered"],
        failure=["table_no_data_rows"],
        recovery=["reobserve_after_loading"],
    ),
    _rule(
        code="TABLE-VIRTUAL-SCROLL-v1",
        name="虚拟滚动表格识别",
        rule_type="table_detection",
        intent="detect_virtual_scroll_table",
        priority=90,
        match={"signals": ["virtual", "scroll", "translateY", "vxe-table", "rc-virtual-list"]},
        action={"detectViewportRows": True, "scrollToLoadMore": True, "preserveRowRefs": True},
        success=["virtual_rows_detected"],
        failure=["table_not_found"],
        recovery=["scroll_table_viewport", "request_human_intervention"],
    ),
    _rule(
        code="TABLE-OPERATION-PAGE-NAVIGATION-v1",
        name="表格分页翻页操作",
        rule_type="table_operation",
        intent="query_list",
        priority=130,
        match={"buttonTexts": ["下一页", "上一页", "尾页", "首页"], "container": "pagination"},
        action={"clickPagination": True, "waitForTableRefresh": True},
        success=["page_index_changed", "table_refreshed"],
        failure=["click_no_effect"],
        recovery=["reobserve_pagination", "request_human_intervention"],
    ),
    _rule(
        code="ROW-LOCATE-BY-SINGLE-FIELD-v1",
        name="单字段定位表格行",
        rule_type="table_row_action",
        intent="open_table_row",
        priority=50,
        match={"matchFields": ["编号", "名称", "标题", "申请人", "状态"], "matchMode": ["exact", "contains"]},
        action={"findRowByCellText": True, "recordMatchedColumn": True},
        success=["target_row_found"],
        failure=["table_target_row_not_found"],
        recovery=["try_multi_field_match", "try_pagination"],
    ),
    _rule(
        code="ROW-LOCATE-BY-MULTI-FIELD-v1",
        name="多字段定位表格行",
        rule_type="table_row_action",
        intent="open_table_row",
        priority=55,
        match={"matchFields": ["编号", "名称", "类型", "状态", "申请人"], "allProvidedFieldsMustMatch": True},
        action={"findRowByMultipleCells": True, "scorePartialMatches": True},
        success=["target_row_found_with_high_confidence"],
        failure=["table_target_row_not_found"],
        recovery=["relax_optional_fields", "request_clarification"],
    ),
    _rule(
        code="ROW-CLICK-ACTION-v1",
        name="点击行内操作",
        rule_type="table_row_action",
        intent="click_table_row_action",
        priority=60,
        match={"actionAreaTexts": ["操作"], "actionTexts": ["详情", "查看", "编辑", "修改", "删除", "审批", "审核"]},
        action={"searchWithinMatchedRow": True, "clickActionButton": True, "verifyEffect": True},
        success=["action_clicked", "dialog_or_page_changed"],
        failure=["table_no_action_found", "click_no_effect"],
        recovery=["try_more_actions", "llm_disambiguation"],
    ),
    _rule(
        code="ROW-MORE-ACTIONS-v1",
        name="更多操作菜单",
        rule_type="table_row_action",
        intent="click_table_row_action",
        priority=70,
        match={"moreTexts": ["更多", "...", "操作"], "popupMenu": True},
        action={"openMoreMenu": True, "selectActionByText": True, "verifyPopupClosed": True},
        success=["menu_action_clicked"],
        failure=["table_no_action_found"],
        recovery=["retry_open_more_menu", "request_human_intervention"],
    ),
    _rule(
        code="ROW-OPEN-TODO-v1",
        name="待办行默认办理",
        rule_type="table_row_action",
        intent="process_table_rows",
        priority=45,
        match={
            "positiveActions": ["办理", "处理", "审批", "审核", "查看", "详情", "业务编号链接"],
            "negativeActions": ["查看审批流程", "审批记录", "流程图"],
            "contextSignals": ["我的待办", "待办列表"],
        },
        action={"preferProcessActions": True, "avoidFlowViewActions": True, "openBusinessLinkWhenNoButton": True},
        success=["todo_row_opened"],
        failure=["table_no_action_found"],
        recovery=["try_link_in_first_business_column", "request_human_intervention"],
    ),
    _rule(
        code="ROW-SKIP-NON-PROCESSABLE-v1",
        name="不可操作行跳过",
        rule_type="table_row_action",
        intent="process_table_rows",
        priority=95,
        match={"nonProcessableSignals": ["已处理", "已完成", "无权限", "不可操作", "禁用"], "missingActionPolicy": "skip_when_allowed"},
        action={"recordSkippedRow": True, "continueLoop": True},
        success=["row_skipped_with_reason"],
        failure=["table_row_loop_failed"],
        recovery=["continue_next_row", "summarize_skipped_rows"],
    ),
    _rule(
        code="FORM-FILL-REQUIRED-v1",
        name="必填字段填写",
        rule_type="form_fill",
        intent="fill_form",
        priority=60,
        match={"requiredSignals": ["required", "必填", "*", "不能为空", "请选择", "请输入"], "visibleOnly": True},
        action={"fillRequiredFirst": True, "requestValueWhenNoDefault": True},
        success=["required_fields_filled"],
        failure=["form_required_field_missing"],
        recovery=["use_default_data_rules", "request_clarification"],
    ),
    _rule(
        code="FORM-FILL-DEFAULT-DATA-v1",
        name="表单默认测试数据",
        rule_type="form_fill",
        intent="fill_field",
        priority=80,
        match={"fieldLabels": list(COMMON_FIELD_DEFAULTS.keys()), "unknownBusinessFieldPolicy": "needs_clarification"},
        action={"defaultValues": COMMON_FIELD_DEFAULTS, "explainDefaultsInRuntimeStream": True},
        success=["default_value_generated"],
        failure=["form_required_field_missing"],
        recovery=["request_test_data"],
    ),
    _rule(
        code="FORM-FILL-LABEL-NEARBY-v1",
        name="邻近标签字段定位",
        rule_type="form_fill",
        intent="fill_field",
        priority=65,
        match={"matchBy": ["nearbyText", "formItemLabel", "parentLabel", "aria-label"], "labelInputIdMayDiffer": True},
        action={"locateNearestEditableControl": True, "verifyValueAfterFill": True},
        success=["field_value_equals"],
        failure=["form_required_field_missing"],
        recovery=["page_semantic_extract", "llm_disambiguation"],
    ),
    _rule(
        code="FORM-FILL-SKIP-READONLY-HIDDEN-v1",
        name="跳过只读隐藏字段",
        rule_type="form_fill",
        intent="fill_form",
        priority=75,
        match={"skipStates": ["readonly", "disabled", "hidden", "display:none", "visibility:hidden"]},
        action={"skipReadonly": True, "skipHidden": True, "recordSkippedFields": True},
        success=["non_editable_fields_skipped"],
        failure=["form_required_field_missing"],
        recovery=["continue_visible_fields"],
    ),
    _rule(
        code="FORM-FILL-VALIDATION-RETRY-v1",
        name="校验失败重填",
        rule_type="form_fill",
        intent="fill_form",
        priority=70,
        match={"validationTexts": ["必填", "不能为空", "请选择", "请输入", "格式不正确"]},
        action={"reobserveValidationErrors": True, "refillInvalidFields": True, "retryLimit": 2},
        success=["no_validation_error"],
        failure=["form_required_field_missing"],
        recovery=["request_clarification", "human_intervention"],
        risk="medium",
    ),
    _rule(
        code="DROPDOWN-NATIVE-SELECT-v1",
        name="原生下拉框选择",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=50,
        match={"selectors": ["select"], "controlTypes": ["native_select"]},
        action={"selectOption": True, "verifySelected": True},
        success=["selected_value_visible"],
        failure=["dropdown_option_not_found"],
        recovery=["request_clarification"],
    ),
    _rule(
        code="DROPDOWN-CUSTOM-SELECT-v1",
        name="自定义下拉框选择",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=55,
        match={"libraries": ["Ant Design", "ElementUI", "Vue Select"], "roles": ["combobox", "listbox"]},
        action={"openDropdown": True, "selectVisibleOption": True, "verifySelected": True},
        success=["selected_value_visible"],
        failure=["dropdown_option_not_found"],
        recovery=["retry_open_dropdown", "search_option_text"],
    ),
    _rule(
        code="DROPDOWN-SEARCHABLE-v1",
        name="可搜索下拉框",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=60,
        match={"searchSignals": ["可搜索", "请输入", "搜索"], "allowSearch": True},
        action={"openDropdown": True, "typeSearchText": True, "selectMatchedOption": True},
        success=["selected_value_visible"],
        failure=["dropdown_option_not_found"],
        recovery=["clear_search_and_retry", "request_clarification"],
    ),
    _rule(
        code="DROPDOWN-MULTI-SELECT-v1",
        name="多选下拉框",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=65,
        match={"multiSignals": ["multiple", "多选", "tag", "checkbox"], "allowMultiple": True},
        action={"selectMultipleOptions": True, "verifyAllSelected": True},
        success=["all_selected_values_visible"],
        failure=["dropdown_option_not_found"],
        recovery=["request_target_values"],
    ),
    _rule(
        code="DROPDOWN-REMOTE-SEARCH-v1",
        name="远程搜索下拉框",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=70,
        match={"remoteSignals": ["remote", "ajax", "loading", "搜索后加载"], "requiresSearchText": True},
        action={"typeSearchText": True, "waitOptionsLoaded": True, "selectMatchedOption": True},
        success=["remote_option_selected"],
        failure=["dropdown_option_not_found"],
        recovery=["wait_and_retry", "request_clarification"],
    ),
    _rule(
        code="DROPDOWN-BODY-POPUP-v1",
        name="body 浮层下拉框",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=75,
        match={"popupContainers": ["body", ".ant-select-dropdown", ".el-select-dropdown"], "detachedPopup": True},
        action={"searchGlobalPopupOptions": True, "clickPopupOption": True},
        success=["selected_value_visible"],
        failure=["dropdown_option_not_found"],
        recovery=["retry_open_dropdown"],
    ),
    _rule(
        code="DROPDOWN-VIRTUAL-SCROLL-v1",
        name="虚拟滚动下拉选项",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=80,
        match={"signals": ["virtual", "rc-virtual-list", "el-virtual", "滚动加载"], "optionMayBeHidden": True},
        action={"scrollOptions": True, "searchBeforeScroll": True, "selectMatchedOption": True},
        success=["selected_value_visible"],
        failure=["dropdown_option_not_found"],
        recovery=["search_option_text", "request_clarification"],
    ),
    _rule(
        code="DROPDOWN-DEFAULT-OPTION-v1",
        name="下拉默认选项策略",
        rule_type="dropdown",
        intent="select_dropdown",
        priority=85,
        match={"defaultableFields": ["状态", "是否", "审批结果", "类型"], "criticalFieldPolicy": "needs_clarification"},
        action={"defaults": {"状态": ["启用", "有效", "正常"], "是否": "是", "审批结果": "通过", "类型": "first_available_when_allowed"}},
        success=["default_option_selected_or_clarification_requested"],
        failure=["dropdown_option_not_found"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="DATE-DIRECT-INPUT-v1",
        name="日期直接输入",
        rule_type="date_picker",
        intent="select_date",
        priority=50,
        match={"controlTypes": ["date_input", "datetime_input"], "preferDirectInput": True},
        action={"fillDateText": True, "verifyValue": True, "dateFormats": ["YYYY-MM-DD", "YYYY/MM/DD", "YYYY-MM-DD HH:mm:ss"]},
        success=["date_value_visible"],
        failure=["date_not_selectable"],
        recovery=["open_date_picker_popup"],
    ),
    _rule(
        code="DATE-PICKER-POPUP-v1",
        name="日期选择器弹层",
        rule_type="date_picker",
        intent="select_date",
        priority=55,
        match={"popupSignals": ["datepicker", "calendar", "日期选择", ".ant-picker-dropdown", ".el-picker-panel"]},
        action={"openPicker": True, "chooseDate": True, "confirmIfNeeded": True},
        success=["date_value_visible"],
        failure=["date_not_selectable"],
        recovery=["choose_next_enabled_date"],
    ),
    _rule(
        code="DATE-RANGE-v1",
        name="日期范围选择",
        rule_type="date_picker",
        intent="select_date_range",
        priority=60,
        match={"fieldLabels": ["开始日期", "结束日期", "起止时间", "有效期"], "range": True},
        action={"defaultValues": DATE_DEFAULTS, "fillStartAndEnd": True, "verifyRange": True},
        success=["date_range_visible"],
        failure=["date_not_selectable"],
        recovery=["choose_next_enabled_date", "request_clarification"],
    ),
    _rule(
        code="DATE-TIME-v1",
        name="日期时间选择",
        rule_type="date_picker",
        intent="select_date",
        priority=65,
        match={"controlTypes": ["datetime_picker", "time_picker"], "formats": ["YYYY-MM-DD HH:mm:ss", "YYYY-MM-DD HH:mm"]},
        action={"fillDateTime": True, "defaultTime": "09:00:00", "verifyValue": True},
        success=["datetime_value_visible"],
        failure=["date_not_selectable"],
        recovery=["open_picker_popup", "request_clarification"],
    ),
    _rule(
        code="DATE-DISABLED-FALLBACK-v1",
        name="禁用日期兜底选择",
        rule_type="date_picker",
        intent="select_date",
        priority=70,
        match={"disabledSignals": ["disabled", "不可选", "禁用日期"], "fallback": "next_available_date"},
        action={"chooseNextEnabledDate": True, "recordDefaultReason": True},
        success=["enabled_date_selected"],
        failure=["date_not_selectable"],
        recovery=["request_clarification"],
    ),
    _rule(
        code="ORG-TREE-SELECT-v1",
        name="组织部门树选择",
        rule_type="org_selector",
        intent="select_org",
        priority=50,
        match={"fieldLabels": ["组织机构", "部门", "所属部门", "单位"], "controlTypes": ["tree", "tree_select"]},
        action={"openTree": True, "searchOrExpand": True, "selectNode": True, "confirmIfNeeded": True},
        success=["organization_value_backfilled"],
        failure=["org_value_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="ORG-MODAL-SELECT-v1",
        name="弹窗选择机构",
        rule_type="org_selector",
        intent="select_org",
        priority=55,
        match={"dialogSignals": ["选择机构", "选择部门", "组织机构"], "containsTree": True},
        action={"openSelectorDialog": True, "selectOrgNode": True, "confirm": True},
        success=["organization_value_backfilled"],
        failure=["org_value_missing", "dialog_not_found"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="ORG-DROPDOWN-TREE-v1",
        name="下拉树选择机构",
        rule_type="org_selector",
        intent="select_org",
        priority=60,
        match={"controlTypes": ["dropdown_tree", "tree_select"], "fieldLabels": ["所属机构", "所属单位"]},
        action={"openDropdownTree": True, "expandTree": True, "selectNode": True},
        success=["organization_value_backfilled"],
        failure=["org_value_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="ORG-SEARCH-v1",
        name="搜索机构",
        rule_type="org_selector",
        intent="select_org",
        priority=65,
        match={"searchSignals": ["搜索机构", "搜索部门", "请输入机构"], "valueProvidedRequired": True},
        action={"searchOrgName": True, "selectMatchedOrg": True, "confirmIfNeeded": True},
        success=["organization_value_backfilled"],
        failure=["org_value_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="ORG-REQUIRE-CLARIFICATION-v1",
        name="关键机构字段追问",
        rule_type="org_selector",
        intent="select_org",
        priority=40,
        match={"criticalLabels": ["组织机构", "所属机构", "部门", "所属部门", "单位", "所属单位"], "noUserValuePolicy": "needs_clarification"},
        action={"askForOrganization": True, "doNotSelectRandomOrg": True},
        success=["clarification_requested"],
        failure=["org_value_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="PERSON-MODAL-SELECT-v1",
        name="人员选择弹窗",
        rule_type="person_selector",
        intent="select_person",
        priority=50,
        match={"dialogSignals": ["选择人员", "选择用户", "人员选择"], "fieldLabels": ["人员", "负责人", "经办人", "申请人", "审批人"]},
        action={"openPersonDialog": True, "selectPerson": True, "confirmIfNeeded": True},
        success=["person_value_backfilled"],
        failure=["person_value_missing", "dialog_not_found"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="PERSON-SEARCH-v1",
        name="人员搜索选择",
        rule_type="person_selector",
        intent="select_person",
        priority=55,
        match={"searchSignals": ["姓名", "工号", "账号", "搜索人员"], "valueProvidedRequired": True},
        action={"searchPerson": True, "selectMatchedPerson": True, "verifyBackfill": True},
        success=["person_value_backfilled"],
        failure=["person_value_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="PERSON-DEPT-TREE-v1",
        name="部门人员树选择",
        rule_type="person_selector",
        intent="select_person",
        priority=60,
        match={"treeSignals": ["部门树", "组织树", "人员树"], "fieldLabels": ["人员", "负责人", "经办人"]},
        action={"expandDepartmentTree": True, "selectPersonNode": True, "confirmIfNeeded": True},
        success=["person_value_backfilled"],
        failure=["person_value_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="PERSON-CURRENT-USER-v1",
        name="当前用户默认人员",
        rule_type="person_selector",
        intent="select_person",
        priority=75,
        match={"defaultableLabels": ["申请人", "经办人"], "defaultSource": "current_user"},
        action={"useCurrentUserWhenAllowed": True, "explainDefault": True},
        success=["current_user_selected"],
        failure=["person_value_missing"],
        recovery=["request_clarification"],
        risk="low",
    ),
    _rule(
        code="PERSON-APPROVER-CLARIFY-v1",
        name="审批人字段追问",
        rule_type="person_selector",
        intent="select_person",
        priority=40,
        match={"criticalLabels": ["审批人", "审核人", "批准人"], "noUserValuePolicy": "needs_clarification"},
        action={"askForApprover": True, "doNotSelectRandomPerson": True},
        success=["clarification_requested"],
        failure=["person_value_missing"],
        recovery=["request_clarification"],
        risk="high",
    ),
    _rule(
        code="TREE-SELECT-NODE-v1",
        name="选择树节点",
        rule_type="tree_selector",
        intent="select_tree_node",
        priority=50,
        match={"treeTypes": ["分类树", "区域树", "设备树", "字典树", "机构树"], "nodeTextProvided": True},
        action={"expandParents": True, "selectNode": True, "verifySelected": True},
        success=["tree_node_selected"],
        failure=["table_target_row_not_found"],
        recovery=["search_tree_node", "expand_lazy_tree"],
    ),
    _rule(
        code="TREE-SEARCH-NODE-v1",
        name="搜索树节点",
        rule_type="tree_selector",
        intent="select_tree_node",
        priority=55,
        match={"searchSignals": ["搜索", "请输入", "筛选"], "treeSearch": True},
        action={"typeSearchText": True, "selectSearchResult": True},
        success=["tree_node_selected"],
        failure=["table_target_row_not_found"],
        recovery=["expand_tree_and_retry"],
    ),
    _rule(
        code="DIALOG-OPEN-SELECTOR-v1",
        name="打开选择弹窗",
        rule_type="dialog_selector",
        intent="select_from_dialog",
        priority=50,
        match={"triggerTexts": ["选择", "请选择", "选择人员", "选择设备", "选择机构"]},
        action={"clickSelectorTrigger": True, "waitDialogVisible": True},
        success=["dialog_visible"],
        failure=["dialog_not_found"],
        recovery=["try_nearby_select_button"],
    ),
    _rule(
        code="DIALOG-QUERY-AND-SELECT-v1",
        name="弹窗查询并选择",
        rule_type="dialog_selector",
        intent="select_from_dialog",
        priority=55,
        match={"dialogContains": ["查询", "搜索", "表格"], "targetValueProvided": True},
        action={"fillDialogQuery": True, "clickQuery": True, "selectMatchedRow": True},
        success=["row_selected_in_dialog"],
        failure=["table_target_row_not_found"],
        recovery=["request_clarification"],
    ),
    _rule(
        code="DIALOG-CONFIRM-SELECTION-v1",
        name="确认弹窗选择",
        rule_type="dialog_selector",
        intent="select_from_dialog",
        priority=60,
        match={"confirmTexts": ["确定", "确认", "选择", "保存"]},
        action={"clickConfirm": True, "waitDialogClosed": True},
        success=["dialog_closed"],
        failure=["click_no_effect"],
        recovery=["try_footer_confirm_button"],
    ),
    _rule(
        code="DIALOG-VERIFY-FILLBACK-v1",
        name="验证选择回填",
        rule_type="dialog_selector",
        intent="select_from_dialog",
        priority=65,
        match={"backfillSignals": ["字段值变化", "标签回显", "输入框回填"]},
        action={"verifyBackfill": True, "captureEvidence": True},
        success=["field_backfilled"],
        failure=["assertion_not_met"],
        recovery=["retry_dialog_selection"],
    ),
    _rule(
        code="FILE-UPLOAD-CUSTOM-BUTTON-v1",
        name="自定义上传按钮",
        rule_type="file_upload",
        intent="upload_file",
        priority=55,
        match={"buttonTexts": ["上传", "选择文件", "添加附件"], "hiddenInputMayAppear": True},
        action={"clickUploadButton": True, "setInputFilesAfterInputAppears": True},
        success=["file_name_visible", "upload_success_message"],
        failure=["form_required_field_missing"],
        recovery=["request_file_path"],
        risk="medium",
    ),
    _rule(
        code="FILE-UPLOAD-DRAG-v1",
        name="拖拽上传区域",
        rule_type="file_upload",
        intent="upload_file",
        priority=65,
        match={"dropzoneSignals": ["拖拽", "拖放", "dropzone", "上传区域"]},
        action={"setInputFilesWhenAvailable": True, "fallbackToUploadButton": True},
        success=["attachment_list_updated"],
        failure=["form_required_field_missing"],
        recovery=["request_file_path"],
        risk="medium",
    ),
    _rule(
        code="FILE-UPLOAD-REQUIRE-FILE-v1",
        name="上传文件必需输入",
        rule_type="file_upload",
        intent="upload_file",
        priority=40,
        match={"requiresUserFile": True, "noFileProvidedPolicy": "needs_clarification"},
        action={"askForFilePath": True, "doNotUploadUnknownFile": True},
        success=["clarification_requested"],
        failure=["form_required_field_missing"],
        recovery=["request_file_path"],
        risk="medium",
    ),
    _rule(
        code="DETAIL-CLICK-ID-LINK-v1",
        name="点击编号链接打开详情",
        rule_type="detail_navigation",
        intent="view_detail",
        priority=50,
        match={"linkColumns": ["申请编号", "业务编号", "单号", "标题", "名称"], "linkLikeCell": True},
        action={"clickBusinessIdLink": True, "verifyDetailContent": True},
        success=["detail_page_or_dialog_visible"],
        failure=["click_no_effect"],
        recovery=["try_row_detail_action"],
    ),
    _rule(
        code="DETAIL-OPEN-DIALOG-v1",
        name="弹窗详情",
        rule_type="detail_navigation",
        intent="view_detail",
        priority=55,
        match={"detailSignals": ["详情", "查看"], "opens": "dialog"},
        action={"clickDetail": True, "waitDialogVisible": True},
        success=["detail_dialog_visible"],
        failure=["dialog_not_found"],
        recovery=["try_drawer_or_page_detail"],
    ),
    _rule(
        code="DETAIL-OPEN-DRAWER-v1",
        name="抽屉详情",
        rule_type="detail_navigation",
        intent="view_detail",
        priority=60,
        match={"detailSignals": ["详情", "查看"], "opens": "drawer"},
        action={"clickDetail": True, "waitDrawerVisible": True},
        success=["detail_drawer_visible"],
        failure=["dialog_not_found"],
        recovery=["try_dialog_or_page_detail"],
    ),
    _rule(
        code="DETAIL-NEW-TAB-v1",
        name="新标签详情",
        rule_type="detail_navigation",
        intent="view_detail",
        priority=65,
        match={"targetBlank": True, "newPageSignals": ["详情", "明细"]},
        action={"expectNewPage": True, "switchToNewPage": True},
        success=["new_tab_detail_visible"],
        failure=["click_no_effect"],
        recovery=["stay_current_page_and_verify"],
    ),
    _rule(
        code="DETAIL-VERIFY-CONTENT-v1",
        name="详情内容验证",
        rule_type="detail_navigation",
        intent="view_detail",
        priority=70,
        match={"contentSignals": ["详情", "明细", "基本信息", "申请信息"], "mustContainBusinessFields": True},
        action={"verifyDetailFields": True, "captureEvidence": True},
        success=["detail_content_visible"],
        failure=["assertion_not_met"],
        recovery=["wait_and_reobserve"],
    ),
    _rule(
        code="APPROVAL-SUBMIT-v1",
        name="提交审批",
        rule_type="approval_workflow",
        intent="submit_for_approval",
        priority=70,
        match={"positiveActions": ["提交审批", "提交审核", "发起审批"], "negativeActions": ["查看审批流程", "审批记录"]},
        action={"clickSubmitApproval": True, "confirmIfNeeded": True},
        success=["submit_success_message", "status_changed_to_pending"],
        failure=["click_no_effect", "permission_denied"],
        recovery=["request_human_confirmation"],
        risk="high",
    ),
    _rule(
        code="APPROVAL-REJECT-v1",
        name="审批驳回",
        rule_type="approval_workflow",
        intent="approval_reject",
        priority=65,
        match={"positiveActions": ["驳回", "退回", "不同意"], "negativeActions": ["查看审批流程", "审批记录"]},
        action={"clickReject": True, "fillOpinionIfNeeded": True, "confirmIfNeeded": True},
        success=["reject_success_message", "status_changed_to_rejected"],
        failure=["click_no_effect", "permission_denied"],
        recovery=["request_human_confirmation"],
        risk="high",
    ),
    _rule(
        code="APPROVAL-FILL-OPINION-v1",
        name="填写审批意见",
        rule_type="approval_workflow",
        intent="fill_field",
        priority=80,
        match={"fieldLabels": ["审批意见", "审核意见", "处理意见"], "defaultText": "自动化测试审批通过"},
        action={"fillOpinion": True, "defaultOpinion": "自动化测试审批通过"},
        success=["opinion_field_filled"],
        failure=["form_required_field_missing"],
        recovery=["request_clarification"],
        risk="medium",
    ),
    _rule(
        code="APPROVAL-CONFIRM-v1",
        name="审批确认",
        rule_type="approval_workflow",
        intent="approval_pass",
        priority=85,
        match={"confirmTexts": ["确定", "确认", "提交", "通过"], "dialogSignals": ["确认", "提示"]},
        action={"confirmApproval": True, "waitResult": True},
        success=["approval_success_message", "status_changed"],
        failure=["click_no_effect"],
        recovery=["request_human_confirmation"],
        risk="high",
    ),
    _rule(
        code="APPROVAL-VIEW-FLOW-v1",
        name="查看审批流程",
        rule_type="approval_workflow",
        intent="view_flow",
        priority=90,
        match={"positiveActions": ["查看审批流程", "审批流程", "流程图"], "mustNotTriggerApprovalPass": True},
        action={"clickFlowView": True, "doNotClickApprovalPass": True},
        success=["approval_flow_visible"],
        failure=["click_no_effect"],
        recovery=["try_approval_record"],
    ),
    _rule(
        code="APPROVAL-VIEW-RECORD-v1",
        name="查看审批记录",
        rule_type="approval_workflow",
        intent="view_flow",
        priority=95,
        match={"positiveActions": ["审批记录", "审批历史", "流转记录"], "mustNotTriggerApprovalPass": True},
        action={"clickApprovalRecord": True, "verifyRecordVisible": True},
        success=["approval_record_visible"],
        failure=["click_no_effect"],
        recovery=["try_flow_view"],
    ),
    _rule(
        code="ASSERT-MULTI-EVIDENCE-v1",
        name="多证据断言",
        rule_type="assertion",
        intent="assert_result",
        priority=50,
        match={"evidenceTypes": ["text", "url", "table", "toast", "status", "breadcrumb"], "allowWeakEvidenceCombination": True},
        action={"collectMultipleEvidence": True, "scoreEvidence": True},
        success=["enough_evidence_collected"],
        failure=["assertion_not_met"],
        recovery=["wait_and_reobserve", "optional_vision_check"],
    ),
    _rule(
        code="ASSERT-TABLE-RECORD-EXISTS-v1",
        name="断言表格记录存在",
        rule_type="assertion",
        intent="assert_result",
        priority=60,
        match={"target": "table_record", "expect": "exists"},
        action={"findRecordInTable": True, "tryPagination": True},
        success=["record_exists"],
        failure=["assertion_not_met", "table_target_row_not_found"],
        recovery=["refresh_table", "request_clarification"],
    ),
    _rule(
        code="ASSERT-TABLE-RECORD-NOT-EXISTS-v1",
        name="断言表格记录不存在",
        rule_type="assertion",
        intent="assert_result",
        priority=65,
        match={"target": "table_record", "expect": "not_exists"},
        action={"searchRecordInTable": True, "treatNoDataAsPass": True},
        success=["record_not_exists"],
        failure=["assertion_not_met"],
        recovery=["refresh_table"],
    ),
    _rule(
        code="ASSERT-TOAST-SUCCESS-v1",
        name="成功提示断言",
        rule_type="assertion",
        intent="assert_result",
        priority=55,
        match={"toastTexts": ["成功", "保存成功", "提交成功", "操作成功", "审批成功"]},
        action={"waitToast": True, "captureMessage": True},
        success=["success_toast_visible"],
        failure=["assertion_not_met"],
        recovery=["check_status_changed", "check_table_refresh"],
    ),
    _rule(
        code="RECOVERY-WAIT-AND-RETRY-v1",
        name="等待后重试",
        rule_type="recovery_policy",
        intent="assert_result",
        priority=50,
        match={"failureTypes": ["click_no_effect", "table_not_found", "assertion_not_met"], "loadingLikely": True},
        action={"waitMs": 1000, "retryLimit": 2, "reobserveBeforeRetry": True},
        success=["retry_succeeded"],
        failure=["click_no_effect"],
        recovery=["ask_human"],
    ),
    _rule(
        code="RECOVERY-RELOAD-PAGE-v1",
        name="刷新页面恢复",
        rule_type="recovery_policy",
        intent="assert_result",
        priority=70,
        match={"failureTypes": ["navigation_goal_not_reached", "table_not_found"], "stalePageLikely": True},
        action={"reloadPage": True, "waitForPageReady": True, "retryCurrentStep": True},
        success=["page_recovered"],
        failure=["navigation_goal_not_reached"],
        recovery=["ask_human"],
        risk="medium",
    ),
    _rule(
        code="RECOVERY-REOBSERVE-PAGE-v1",
        name="重新观察页面",
        rule_type="recovery_policy",
        intent="assert_result",
        priority=55,
        match={"failureTypes": ["menu_child_not_found", "table_no_action_found", "form_required_field_missing"], "pageMayHaveChanged": True},
        action={"reobservePage": True, "rerankCandidates": True},
        success=["new_candidates_found"],
        failure=["assertion_not_met"],
        recovery=["llm_disambiguation"],
    ),
    _rule(
        code="RECOVERY-LLM-DISAMBIGUATION-v1",
        name="LLM 候选消歧",
        rule_type="recovery_policy",
        intent="assert_result",
        priority=80,
        match={"failureTypes": ["table_no_action_found", "click_no_effect"], "ambiguousCandidates": True},
        action={"callLlmResolver": True, "recordPromptKey": True},
        success=["llm_selected_candidate"],
        failure=["assertion_not_met"],
        recovery=["vision_optional", "ask_human"],
        risk="medium",
    ),
    _rule(
        code="RECOVERY-VISION-OPTIONAL-v1",
        name="可选视觉兜底",
        rule_type="recovery_policy",
        intent="assert_result",
        priority=90,
        match={"failureTypes": ["click_no_effect", "assertion_not_met"], "visionIsOptional": True},
        action={"callVisionWhenConfigured": True, "doNotUseVisionNotConfiguredAsPrimaryFailure": True},
        success=["vision_candidate_found_or_optional_skipped"],
        failure=["vision_fallback_not_configured"],
        recovery=["ask_human"],
        risk="medium",
    ),
    _rule(
        code="RECOVERY-ASK-HUMAN-v1",
        name="请求人工介入",
        rule_type="recovery_policy",
        intent="assert_result",
        priority=100,
        match={"failureTypes": ["permission_denied", "forced_password_change", "org_value_missing", "person_value_missing"], "noSafeAutomaticRecovery": True},
        action={"createHumanIntervention": True, "preserveFailureEvidence": True},
        success=["human_intervention_created"],
        failure=["permission_denied"],
        recovery=["manual_resolution"],
        risk="high",
    ),
]
